import { useEffect, useState } from "react";
import "./App.css";
import Chat from "./Components/Chat";
import Navbar from "./Components/Navbar";
import useGlobalState from "./State/GlobalState";

function App() {
  // const [user, setUser] = useState("");
  const [user, setUser] = useGlobalState("user");
  const [room, setRoom] = useGlobalState("room");
  const [userSet, setUserSet] = useState(false);
  /* const [room, setRoom] = useState({
    room: "random-room",
    autoGenerated: true,
  }); */

  useEffect(() => {
    const urlParamRoom = new URLSearchParams(window.location.search).get(
      "room"
    );

    /* const room =  
      (urlParamRoom && urlParamRoom.toString().toLowerCase().trim()) ||
      "random-room";
    */

    if (urlParamRoom) {
      setRoom({
        name: urlParamRoom && urlParamRoom.toString().toLowerCase().trim(),
        autoGenerated: false,
      });

      // localStorage.setItem("chat-app-room", JSON.stringify(room));
    }

    // localStorage.setItem("chat-app-room", JSON.stringify(room));

    return () => {
      // localStorage.removeItem("chat-app-user");
      // localStorage.removeItem("chat-app-room");
    };
    // eslint-disable-next-line
  }, []);

  const setUserName = () => (
    <div className="container d-flex justify-content-center align-items-center custom-username-input">
      <div className="m-4 p-4 border border-info rounded-3 text-start">
        <div className="mb-3">
          <label htmlFor="username" className="form-label">
            Your Username
          </label>
          <input
            type="text"
            className="form-control"
            id="username"
            onChange={(e) => setUser(e.target.value)}
            value={user}
            required={true}
            placeholder="Username"
          />
        </div>

        <div className="d-grid gap-2">
          <button
            className="btn btn-outline-info"
            type="button"
            onClick={(e) => {
              e.preventDefault();
              if (user && user !== "") {
                // localStorage.setItem("chat-app-user", user);
                // localStorage.setItem("chat-app-room", JSON.stringify(room));

                setUserSet(true);
              }
            }}
          >
            {`${room.autoGenerated === true ? "Create and " : ""}`}Join Room
          </button>
        </div>
      </div>
    </div>
  );

  return (
    <div className="App">
      {/* <header className="App-header">Hello</header> */}
      <Navbar userSet={userSet} />
      <div className="bg-dark text-light h-100">
        {user && userSet && user !== "" ? <Chat /> : setUserName()}
      </div>
    </div>
  );
}

export default App;
